FROM registry.access.redhat.com/rhel6.8

MAINTAINER FZT <email>

COPY yum-3.2.29-81.el6.centos.noarch.rpm \
     yum-metadata-parser-1.1.2-16.el6.x86_64.rpm \
     yum-plugin-fastestmirror-1.1.30-41.el6.noarch.rpm \
     rhel-source.repo \
     /opt/
    
RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo 'Asia/Shanghai' > /etc/timezone && \
    rpm -qa | grep yum | xargs rpm -e --nodeps && \
    cd /opt/ && \
    rpm -ivh yum-metadata-parser-1.1.2-16.el6.x86_64.rpm && \
    rpm -ivh yum-3.2.29-81.el6.centos.noarch.rpm yum-plugin-fastestmirror-1.1.30-41.el6.noarch.rpm && \
    cp /opt/rhel-source.repo /etc/yum.repos.d/rhel-source.repo && \
    yum makecache && \
    yum update -y && \
    yum clean all  && \
    rm -fr /opt/*